apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-catalog-service
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: quest-catalog-service
  template:
    metadata:
      labels:
        app: quest-catalog-service
    spec:
      containers:
      - name: quest-catalog-service
        image: soundwavexmx2/quest-catalog-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: PORT
          value: "80"
        - name: QUEST_PROCESSING_URL
          value: "http://quest-processing-service:80"
        - name: USER_AUTH_URL
          value: "http://user-auth-service:80"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:80"
        - name: DB_HOST
          value: "quest-catalog-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "catalog_user"
        - name: DB_PASSWORD
          value: "catalog_pass"
        - name: DB_NAME
          value: "quest-catalog-db"      
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
