apiVersion: apps/v1
kind: Deployment
metadata:
  name: quest-catalog-db
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quest-catalog-db
  template:
    metadata:
      labels:
        app: quest-catalog-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: catalog_user
        - name: POSTGRES_PASSWORD
          value: catalog_pass
        - name: POSTGRES_DB
          value: quest-catalog-db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
