apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-db
  namespace: app-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-auth-db
  template:
    metadata:
      labels:
        app: user-auth-db
    spec:
      containers:
      - name: postgres
        image: postgres:latest
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: auth_user
        - name: POSTGRES_PASSWORD
          value: auth_pass
        - name: POSTGRES_DB
          value: user_auth_db
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-storage
      volumes:
      - name: postgres-storage
        emptyDir: {}
