apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-auth-service
  namespace: app-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user-auth-service
  template:
    metadata:
      labels:
        app: user-auth-service
    spec:
      containers:
      - name: user-auth-service
        image: soundwavexmx2/user-auth-service:latest
        ports:
        - containerPort: 8000
        env:
        - name: QUEST_PROCESSING_URL
          value: "http://quest-processing-service:8000"
        - name: QUEST_CATALOG_URL
          value: "http://quest-catalog-service:8000"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8000"
        - name: DB_HOST
          value: "user-auth-db"
        - name: DB_PORT
          value: "5432"
        - name: DB_USER
          value: "auth_user"
        - name: DB_PASSWORD
          value: "auth_pass"
        - name: DB_NAME
          value: "user-auth-db"          
        resources:
          requests:
            memory: "128Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
