networks:
  app_network:
    driver: bridge

services:
  user_auth_service:
    build:
      context: ./user_auth_service
    container_name: user_auth_service
    ports:
      - "8001:8000"
    environment:
      DATABASE_URL: postgres://auth_user:auth_pass@user_auth_db:5432/user_auth_db
    depends_on:
      - user_auth_db
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  user_auth_db:
    image: postgres:13
    container_name: user_auth_db
    environment:
      POSTGRES_USER: auth_user
      POSTGRES_PASSWORD: auth_pass
      POSTGRES_DB: user_auth_db
    ports:
      - "5432:5432"
    volumes:
      - user_auth_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "auth_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network    

  quest_catalog_service:
    build:
      context: ./quest_catalog_service
    container_name: quest_catalog_service
    environment:
      DATABASE_URL: postgres://catalog_user:catalog_pass@quest_catalog_db:5432/quest_catalog_db
    depends_on:
      - quest_catalog_db
    ports:
      - "8002:8000"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  quest_catalog_db:
    image: postgres:13
    container_name: quest_catalog_db
    environment:
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_pass
      POSTGRES_DB: quest_catalog_db
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "catalog_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - quest_catalog_data:/var/lib/postgresql/data
    networks:
      - app_network

  quest_processing_service:
    build:
      context: ./quest_processing_service
    container_name: quest_processing_service
    ports:
      - "8003:8000"
    environment:
      DATABASE_URL: postgres://processing_user:processing_pass@quest_processing_db:5432/quest_processing_db
      QUEST_CATALOG_URL: http://quest_catalog_service:8000
    depends_on:
      - quest_processing_db
      - quest_catalog_service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

  quest_processing_db:
    image: postgres:13
    container_name: quest_processing_db
    environment:
      POSTGRES_USER: processing_user
      POSTGRES_PASSWORD: processing_pass
      POSTGRES_DB: quest_processing_db
    ports:
      - "5434:5432"
    volumes:
      - quest_processing_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "processing_user"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network


  api_gateway:
    build:
      context: ./api_gateway
    container_name: api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - user_auth_service
      - quest_catalog_service
      - quest_processing_service
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - app_network

volumes:
  user_auth_data:
  quest_catalog_data:
  quest_processing_data:

